name: LateX to PDF

on:
  push:
    branches: 
      - main
      - develop
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX to PDF
        run: docker run --rm -i -v $(pwd):/data mingc/latex pdflatex main.tex
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: main.pdf      
      - name: Create GitHub Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} 
        with:
          tag_name: latest
          release_name: latest
          body: |
            This is an automated release created by the GitHub Actions workflow.
          draft: false
          prerelease: false
          files:
            - name: PDF
              path: main.pdf
          overwrite: true
